// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.projet.grpc.stubs;

public interface GetSummaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetSummaryRequest)
    com.google.protobuf.MessageOrBuilder {
}
