// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.projet.grpc.stubs;

/**
 * Protobuf type {@code GetSummaryResponse}
 */
public  final class GetSummaryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetSummaryResponse)
    GetSummaryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSummaryResponse.newBuilder() to construct.
  private GetSummaryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSummaryResponse() {
    summaries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSummaryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSummaryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              summaries_ = new java.util.ArrayList<ma.projet.grpc.stubs.TypeCompteSummary>();
              mutable_bitField0_ |= 0x00000001;
            }
            summaries_.add(
                input.readMessage(ma.projet.grpc.stubs.TypeCompteSummary.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        summaries_ = java.util.Collections.unmodifiableList(summaries_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ma.projet.grpc.stubs.CompteServiceOuterClass.internal_static_GetSummaryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ma.projet.grpc.stubs.CompteServiceOuterClass.internal_static_GetSummaryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ma.projet.grpc.stubs.GetSummaryResponse.class, ma.projet.grpc.stubs.GetSummaryResponse.Builder.class);
  }

  public static final int SUMMARIES_FIELD_NUMBER = 1;
  private java.util.List<ma.projet.grpc.stubs.TypeCompteSummary> summaries_;
  /**
   * <code>repeated .TypeCompteSummary summaries = 1;</code>
   */
  public java.util.List<ma.projet.grpc.stubs.TypeCompteSummary> getSummariesList() {
    return summaries_;
  }
  /**
   * <code>repeated .TypeCompteSummary summaries = 1;</code>
   */
  public java.util.List<? extends ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder> 
      getSummariesOrBuilderList() {
    return summaries_;
  }
  /**
   * <code>repeated .TypeCompteSummary summaries = 1;</code>
   */
  public int getSummariesCount() {
    return summaries_.size();
  }
  /**
   * <code>repeated .TypeCompteSummary summaries = 1;</code>
   */
  public ma.projet.grpc.stubs.TypeCompteSummary getSummaries(int index) {
    return summaries_.get(index);
  }
  /**
   * <code>repeated .TypeCompteSummary summaries = 1;</code>
   */
  public ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder getSummariesOrBuilder(
      int index) {
    return summaries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < summaries_.size(); i++) {
      output.writeMessage(1, summaries_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < summaries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, summaries_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ma.projet.grpc.stubs.GetSummaryResponse)) {
      return super.equals(obj);
    }
    ma.projet.grpc.stubs.GetSummaryResponse other = (ma.projet.grpc.stubs.GetSummaryResponse) obj;

    if (!getSummariesList()
        .equals(other.getSummariesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSummariesCount() > 0) {
      hash = (37 * hash) + SUMMARIES_FIELD_NUMBER;
      hash = (53 * hash) + getSummariesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.GetSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ma.projet.grpc.stubs.GetSummaryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetSummaryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetSummaryResponse)
      ma.projet.grpc.stubs.GetSummaryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.projet.grpc.stubs.CompteServiceOuterClass.internal_static_GetSummaryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.projet.grpc.stubs.CompteServiceOuterClass.internal_static_GetSummaryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.projet.grpc.stubs.GetSummaryResponse.class, ma.projet.grpc.stubs.GetSummaryResponse.Builder.class);
    }

    // Construct using ma.projet.grpc.stubs.GetSummaryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSummariesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (summariesBuilder_ == null) {
        summaries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        summariesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ma.projet.grpc.stubs.CompteServiceOuterClass.internal_static_GetSummaryResponse_descriptor;
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.GetSummaryResponse getDefaultInstanceForType() {
      return ma.projet.grpc.stubs.GetSummaryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.GetSummaryResponse build() {
      ma.projet.grpc.stubs.GetSummaryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.GetSummaryResponse buildPartial() {
      ma.projet.grpc.stubs.GetSummaryResponse result = new ma.projet.grpc.stubs.GetSummaryResponse(this);
      int from_bitField0_ = bitField0_;
      if (summariesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          summaries_ = java.util.Collections.unmodifiableList(summaries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.summaries_ = summaries_;
      } else {
        result.summaries_ = summariesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ma.projet.grpc.stubs.GetSummaryResponse) {
        return mergeFrom((ma.projet.grpc.stubs.GetSummaryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ma.projet.grpc.stubs.GetSummaryResponse other) {
      if (other == ma.projet.grpc.stubs.GetSummaryResponse.getDefaultInstance()) return this;
      if (summariesBuilder_ == null) {
        if (!other.summaries_.isEmpty()) {
          if (summaries_.isEmpty()) {
            summaries_ = other.summaries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSummariesIsMutable();
            summaries_.addAll(other.summaries_);
          }
          onChanged();
        }
      } else {
        if (!other.summaries_.isEmpty()) {
          if (summariesBuilder_.isEmpty()) {
            summariesBuilder_.dispose();
            summariesBuilder_ = null;
            summaries_ = other.summaries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            summariesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSummariesFieldBuilder() : null;
          } else {
            summariesBuilder_.addAllMessages(other.summaries_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ma.projet.grpc.stubs.GetSummaryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ma.projet.grpc.stubs.GetSummaryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ma.projet.grpc.stubs.TypeCompteSummary> summaries_ =
      java.util.Collections.emptyList();
    private void ensureSummariesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        summaries_ = new java.util.ArrayList<ma.projet.grpc.stubs.TypeCompteSummary>(summaries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ma.projet.grpc.stubs.TypeCompteSummary, ma.projet.grpc.stubs.TypeCompteSummary.Builder, ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder> summariesBuilder_;

    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public java.util.List<ma.projet.grpc.stubs.TypeCompteSummary> getSummariesList() {
      if (summariesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(summaries_);
      } else {
        return summariesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public int getSummariesCount() {
      if (summariesBuilder_ == null) {
        return summaries_.size();
      } else {
        return summariesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public ma.projet.grpc.stubs.TypeCompteSummary getSummaries(int index) {
      if (summariesBuilder_ == null) {
        return summaries_.get(index);
      } else {
        return summariesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder setSummaries(
        int index, ma.projet.grpc.stubs.TypeCompteSummary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.set(index, value);
        onChanged();
      } else {
        summariesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder setSummaries(
        int index, ma.projet.grpc.stubs.TypeCompteSummary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.set(index, builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder addSummaries(ma.projet.grpc.stubs.TypeCompteSummary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.add(value);
        onChanged();
      } else {
        summariesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder addSummaries(
        int index, ma.projet.grpc.stubs.TypeCompteSummary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.add(index, value);
        onChanged();
      } else {
        summariesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder addSummaries(
        ma.projet.grpc.stubs.TypeCompteSummary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.add(builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder addSummaries(
        int index, ma.projet.grpc.stubs.TypeCompteSummary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.add(index, builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder addAllSummaries(
        java.lang.Iterable<? extends ma.projet.grpc.stubs.TypeCompteSummary> values) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, summaries_);
        onChanged();
      } else {
        summariesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder clearSummaries() {
      if (summariesBuilder_ == null) {
        summaries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        summariesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public Builder removeSummaries(int index) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.remove(index);
        onChanged();
      } else {
        summariesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public ma.projet.grpc.stubs.TypeCompteSummary.Builder getSummariesBuilder(
        int index) {
      return getSummariesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder getSummariesOrBuilder(
        int index) {
      if (summariesBuilder_ == null) {
        return summaries_.get(index);  } else {
        return summariesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public java.util.List<? extends ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder> 
         getSummariesOrBuilderList() {
      if (summariesBuilder_ != null) {
        return summariesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(summaries_);
      }
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public ma.projet.grpc.stubs.TypeCompteSummary.Builder addSummariesBuilder() {
      return getSummariesFieldBuilder().addBuilder(
          ma.projet.grpc.stubs.TypeCompteSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public ma.projet.grpc.stubs.TypeCompteSummary.Builder addSummariesBuilder(
        int index) {
      return getSummariesFieldBuilder().addBuilder(
          index, ma.projet.grpc.stubs.TypeCompteSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .TypeCompteSummary summaries = 1;</code>
     */
    public java.util.List<ma.projet.grpc.stubs.TypeCompteSummary.Builder> 
         getSummariesBuilderList() {
      return getSummariesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ma.projet.grpc.stubs.TypeCompteSummary, ma.projet.grpc.stubs.TypeCompteSummary.Builder, ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder> 
        getSummariesFieldBuilder() {
      if (summariesBuilder_ == null) {
        summariesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ma.projet.grpc.stubs.TypeCompteSummary, ma.projet.grpc.stubs.TypeCompteSummary.Builder, ma.projet.grpc.stubs.TypeCompteSummaryOrBuilder>(
                summaries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        summaries_ = null;
      }
      return summariesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetSummaryResponse)
  }

  // @@protoc_insertion_point(class_scope:GetSummaryResponse)
  private static final ma.projet.grpc.stubs.GetSummaryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ma.projet.grpc.stubs.GetSummaryResponse();
  }

  public static ma.projet.grpc.stubs.GetSummaryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSummaryResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSummaryResponse>() {
    @java.lang.Override
    public GetSummaryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSummaryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSummaryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSummaryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ma.projet.grpc.stubs.GetSummaryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

