// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.projet.grpc.stubs;

public interface SearchComptesByDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchComptesByDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dateCreation = 1;</code>
   * @return The dateCreation.
   */
  java.lang.String getDateCreation();
  /**
   * <code>string dateCreation = 1;</code>
   * @return The bytes for dateCreation.
   */
  com.google.protobuf.ByteString
      getDateCreationBytes();
}
