// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.projet.grpc.stubs;

public interface TypeCompteSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TypeCompteSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  ma.projet.grpc.stubs.TypeCompte getType();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
